import Head from 'next/head'
import Hero from '../components/Hero'
import Tabs from '../components/Tabs'
import Main from '../components/Main'

export default function Home() {
  return (
    <>
      <Head>
        <title>Govt. Degree College Handwara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Tabs/>
      <Main/>
    </>
  )
}
